
USE TELEPERFORMANCE;

CREATE TABLE HOBBIES
(
	Id INT IDENTITY,
	Name VARCHAR(255),
	CONSTRAINT HOBBIES_ID_PK PRIMARY KEY(Id)
);

CREATE TABLE USERS
(
	Id INT IDENTITY,
	Name VARCHAR(200) NOT NULL,
	UserName VARCHAR(20) NOT NULL,
	Password VARCHAR(32) NOT NULL,
	PhoneNumber VARCHAR(20),
	CONSTRAINT USERS_ID_PK PRIMARY KEY (ID)
);


CREATE TABLE HobbiesUsers
(
	Id INT IDENTITY,	
	UserId INT, 
	HobbieId INT, 
	CONSTRAINT FK_USER_ID FOREIGN KEY (UserId) REFERENCES Users(Id),
	CONSTRAINT FK_HOBBIES_ID FOREIGN KEY (HobbieId) REFERENCES Hobbies(Id),
	CONSTRAINT PK_HOBBIES_USER PRIMARY KEY (Id)
);

INSERT INTO USERS (Name, UserName, Password, PhoneNumber)
VALUES ('Teleperformance', 'teleperformance', CONVERT(VARCHAR(32), HashBytes('MD5', 'Ta*:uKd--douU3*GR_rOU?at-H:vPYIJqwerty987654*'), 2), '+5511947303699');

INSERT INTO HOBBIES(NAME) VALUES ('Pintura'), ('Aulas de teatro'), ('Corrida'), ('Academia'), ('Yoga'), ('Dança');